[[mgr.prepend_keymap]]
desc = "Drag and drop using ripdrag"
on = "<C-n>"
run = "shell 'ripdrag \"$@\" -x 2>/dev/null &' --confirm\n"

[[mgr.prepend_keymap]]
on = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
desc = "Jump to char"
on = "f"
run = "plugin jump-to-char"
