[mgr]
linemode = "size"
ratio = [1, 3, 4]

[[open.rules]]
name = "*/"
use = ["edit", "open", "reveal"]

[[open.rules]]
mime = "text/*"
use = ["edit", "reveal"]

[[open.rules]]
mime = "image/*"
use = ["open", "reveal"]

[[open.rules]]
mime = "{audio,video}/*"
use = ["play", "reveal"]

[[open.rules]]
mime = "application/{json,ndjson}"
use = ["edit", "reveal"]

[[open.rules]]
mime = "*/javascript"
use = ["edit", "reveal"]

[[open.rules]]
mime = "inode/empty"
use = ["edit", "reveal"]

[[open.rules]]
name = "*"
use = ["open", "reveal"]

[[open.rules]]
name = "*.{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}"
use = ["extract", "reveal"]

[[opener.edit]]
block = true
for = "unix"
run = "hx \"$@\""

[[opener.extract]]
desc = "Extract here"
for = "unix"
run = "ya pub extract --list \"$@\""

[[opener.open]]
desc = "Open"
for = "linux"
run = "xdg-open \"$@\""

[[opener.play]]
for = "unix"
orphan = true
run = "xdg-open \"$@\""

[[opener.reveal]]
desc = "Reveal"
for = "linux"
run = "xdg-open \"$(dirname \"$1\")\""

[preview]
max_height = 900
max_width = 1440
ueberzug_scale = 1
