[[keyboard.bindings]]
key = "T"
mods = "Alt|Shift"

[keyboard.bindings.command]
args = ["-e", "wsl", "-d", "NixOS", "--cd", "~", "--shell-type", "login", "--", "tmux", "new"]
program = "alacritty"

[terminal.shell]
args = [
    "-d",
    "NixOS",
    "--cd",
    "~",
    "--shell-type",
    "login",
]
program = "wsl"

[window]
startup_mode = "Maximized"
